# Generated by Django 5.2.16 on 2026-09-09 18:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_role', models.CharField(max_length=20)),
                ('action', models.CharField(choices=[('user_created', 'User Created'), ('user_deactivated', 'User Deactivated'), ('group_created', 'Group Created'), ('student_added', 'Student Added to Group'), ('student_removed', 'Student Removed from Group'), ('guide_assigned', 'Guide Assigned'), ('reviewer_assigned', 'Reviewer Assigned'), ('reviewer_reassigned', 'Reviewer Reassigned'), ('submission_created', 'Submission Created'), ('submission_edited', 'Submission Edited'), ('submission_submitted', 'Submission Submitted'), ('submission_approved', 'Submission Approved'), ('changes_requested', 'Changes Requested'), ('submission_resubmitted', 'Submission Resubmitted'), ('marks_entered', 'Marks Entered'), ('marks_finalized', 'Marks Finalized'), ('marks_corrected', 'Marks Corrected'), ('document_uploaded', 'Document Uploaded'), ('document_replaced', 'Document Replaced'), ('stage_unlocked', 'Stage Unlocked'), ('stage_locked', 'Stage Locked'), ('final_submission_approved', 'Final Submission Approved'), ('group_archived', 'Group Archived'), ('report_generated', 'Report Generated'), ('logbook_generated', 'Logbook Generated')], max_length=50)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.BigIntegerField()),
                ('previous_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='academics.academicyear')),
            ],
            options={
                'db_table': 'deadline',
            },
        ),
    ]
