# Generated by Django 5.2.16 on 2026-09-09 18:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='COPOMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weightage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'db_table': 'co_po_mapping',
            },
        ),
        migrations.CreateModel(
            name='PO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'po',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='POAttainment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normalized_marks', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('attainment_level', models.CharField(blank=True, max_length=50)),
                ('calculated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'po_attainment',
            },
        ),
        migrations.CreateModel(
            name='CO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cos', to='academics.academicyear')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cos', to='academics.department')),
            ],
            options={
                'db_table': 'co',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='COAttainment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_marks', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('max_marks', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('normalized_marks', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('attainment_level', models.CharField(blank=True, max_length=50)),
                ('calculated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('co', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attainments', to='co_po.co')),
            ],
            options={
                'db_table': 'co_attainment',
            },
        ),
    ]
