# Generated by Django 5.2.16 on 2026-09-09 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('co_po', '0001_initial'),
        ('groups', '0002_initial'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coattainment',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_attainments', to='groups.projectgroup'),
        ),
        migrations.AddField(
            model_name='coattainment',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='co_attainments', to='reviews.review'),
        ),
        migrations.AddField(
            model_name='copomapping',
            name='co',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po_mappings', to='co_po.co'),
        ),
        migrations.AddField(
            model_name='po',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos', to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='po',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos', to='academics.department'),
        ),
        migrations.AddField(
            model_name='copomapping',
            name='po',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_mappings', to='co_po.po'),
        ),
        migrations.AddField(
            model_name='poattainment',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po_attainments', to='groups.projectgroup'),
        ),
        migrations.AddField(
            model_name='poattainment',
            name='po',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po_attainments', to='co_po.po'),
        ),
        migrations.AddField(
            model_name='poattainment',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='po_attainments', to='reviews.review'),
        ),
        migrations.AlterUniqueTogether(
            name='coattainment',
            unique_together={('co', 'group', 'review')},
        ),
        migrations.AlterUniqueTogether(
            name='copomapping',
            unique_together={('co', 'po')},
        ),
        migrations.AlterUniqueTogether(
            name='poattainment',
            unique_together={('po', 'group', 'review')},
        ),
    ]
