# Generated by Django 5.2.16 on 2026-09-09 18:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('photograph', 'Student Photograph'), ('synopsis', 'Synopsis'), ('report', 'Project Report'), ('uml_diagram', 'UML Diagram'), ('research_paper', 'Research Paper'), ('certificate', 'Certificate'), ('competition_certificate', 'Competition Certificate'), ('sponsorship_letter', 'Sponsorship Letter'), ('completion_letter', 'Completion Letter'), ('ppt', 'PPT'), ('source_code', 'Source Code'), ('other', 'Other')], max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='uploaded', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('current_version', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'document',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField()),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField()),
                ('mime_type', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('remarks', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'document_version',
                'ordering': ['version_number'],
            },
        ),
    ]
