# Generated by Django 5.2.16 on 2026-09-09 18:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('progress', 'Progress'), ('faculty_workload', 'Faculty Workload'), ('reviewer_workload', 'Reviewer Workload'), ('stage_completion', 'Stage Completion'), ('overdue', 'Overdue'), ('marks', 'Marks'), ('final_submission', 'Final Submission'), ('co_attainment', 'CO Attainment'), ('po_attainment', 'PO Attainment'), ('department_status', 'Department Status')], default='progress', max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('filters', models.JSONField(default=dict)),
                ('format', models.CharField(choices=[('csv', 'CSV'), ('excel', 'Excel'), ('pdf', 'PDF')], default='pdf', max_length=10)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(default='generated', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.academicyear')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'report',
                'ordering': ['-created_at'],
            },
        ),
    ]
