# Generated by Django 5.2.16 on 2026-09-09 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('groups', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectgroup',
            name='current_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_groups', to='projects.projectstage'),
        ),
        migrations.AddField(
            model_name='projectgroup',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='academics.department'),
        ),
        migrations.AddField(
            model_name='projectgroup',
            name='project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='projects.project'),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='groups.projectgroup'),
        ),
        migrations.AddField(
            model_name='projectguideassignment',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='projectguideassignment',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectguideassignment',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide_assignments', to='groups.projectgroup'),
        ),
        migrations.AddField(
            model_name='reviewerassignment',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='reviewerassignment',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewerassignment',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_assignments', to='groups.projectgroup'),
        ),
        migrations.AlterUniqueTogether(
            name='projectgroup',
            unique_together={('academic_year', 'group_number', 'department')},
        ),
        migrations.AlterUniqueTogether(
            name='groupmember',
            unique_together={('group', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='projectguideassignment',
            unique_together={('group', 'faculty', 'academic_year')},
        ),
        migrations.AlterUniqueTogether(
            name='reviewerassignment',
            unique_together={('group', 'faculty', 'academic_year', 'review_number')},
        ),
    ]
