# Generated by Django 5.2.16 on 2026-09-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='acknowledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='contribution',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='students/photos/'),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='status',
            field=models.CharField(choices=[('invited', 'Invited'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='accepted', max_length=20),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='te_result',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
