# Generated by Django 5.2.16 on 2026-09-10 11:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_groupmember_acknowledged_groupmember_acknowledged_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmember',
            name='joined_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='projectguideassignment',
            name='assigned_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='reviewerassignment',
            name='assigned_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
